- name: Configuring dashboard local settings
  copy:
    src: local_settings
    dest: /etc/openstack-dashboard
    owner: root
    group: apache
    mode: 640

  notify: Restarting httpd and memcached 

- name: Configuring openstack dashboard
  copy:
    src:  openstack-dashboard.conf
    dest:  /etc/httpd/conf.d/
    owner: root
    group: root
    mode: 0644

  notify: Restarting httpd and memcached 

